sudo: required

language: node_js
node_js:
  - '8'

services:
  - docker

before_install:
  - docker pull quay.io/coreos/etcd
  - docker run -d -p 2379:2379 quay.io/coreos/etcd etcd -listen-client-urls=http://0.0.0.0:2379 -advertise-client-urls=http://127.0.0.1:2379
  - docker ps -a

script: npm test
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
